# Generated by Django 3.2.3 on 2021-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255)),
                ('short_url', models.CharField(default='', max_length=255)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
