# Generated by Django 3.2.3 on 2021-05-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
